name: "Pull Request - Validation"

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Android Environment"
        uses: ./.github/actions/setup-android

      - name: "Generate google-services.json file"
        run: echo ${{secrets.GOOGLE_SERVICES_KEY}} | base64 -d > app/google-services.json

      - name: "Run unit tests"
        run: ./gradlew testReleaseUnitTest

      - name: "Report Unit Tests Results"
        uses: dorny/test-reporter@v1
        if: success()
        with:
          name: Unit Tests Execution Report
          path: 'app/build/test-results/testReleaseUnitTest/TEST-*.xml'
          reporter: java-junit
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          fail-on-empty: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Check lint"
        run: ./gradlew :app:lintRelease

      - name: "Report lint results"
        uses: hidakatsuya/action-report-android-lint@v1.1.3
        with:
          fail-on-warning: false
          result-path: 'app/build/reports/lint-results-release.xml'

      - name: "Upload lint reports (HTML)"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          retention-days: 3
          path: '**/build/reports/lint-results-*.html'

      - name: "Upload test results (XML)"
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          retention-days: 3
          path: '**/build/test-results/test*UnitTest/**.xml'