name: Build develop branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload test results (XML)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          retention-days: 3
          path: '**/build/test-results/test*UnitTest/**.xml'

      - name: Report Unit Tests Results
        uses: dorny/test-reporter@v1
        if: success()
        with:
          name: Unit Tests Report
          path: 'app/build/reports/lint-results-release.xml'
          reporter: java-junit
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          fail-on-empty: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check lint
        run: ./gradlew :app:lintRelease

      - name: Upload lint reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          retention-days: 3
          path: '**/build/reports/lint-results-*.html'

      - name: Report lint results
        uses: hidakatsuya/action-report-android-lint@v1.1.3
        with:
          result-path: 'app/build/reports/lint-results-release.xml'

      - name: Run JaCoCo Coverage
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo report (XML)
        uses: actions/upload-artifact@v4
        with:
          name: report.xml
          retention-days: 3
          path: ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReleaseUnitTestReport/jacocoTestReleaseUnitTestReport.xml

      - name: JaCoCo coverage reporter - parse xml report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReleaseUnitTestReport/jacocoTestReleaseUnitTestReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      - name: Upload coverage parsed results (XML)
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: "*/coverage-results.md"
          retention-days: 3

      - name: Parse coverage information
        run: |
          echo "Total coverage coverage-overall ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
          echo "Coverage coveragePercentage ${{ steps.jacoco_reporter.outputs.coveragePercentage }}"
          echo "Coverage coveragePercentageString ${{ steps.jacoco_reporter.outputs.coveragePercentageString }}"

      - name: Publish coverage summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY