name: "Release - Internal Testing"

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Android Environment"
        uses: ./.github/actions/setup-android

      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: "Generate google-services.json file"
        run: echo ${{secrets.GOOGLE_SERVICES_KEY}} | base64 -d > app/google-services.json

      - name: "Generate service-account.json file"
        run: echo ${{secrets.SERVICES_ACCOUNT_KEY}} | base64 -d > service-account.json

      - name: "Generate .jks file"
        run: echo ${{secrets.ANDROID_SIGNING_KEY}} | base64 -d > keys/release.jks

      - name: "Upload AAB to Play Store"
        run: bundle exec fastlane internal
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}