name: Create and Upload AAB to internal google play track.

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Apk uploading on Firebase App Distribution
    runs-on: ubuntu-latest

    env:
      ANDROID_KEY_ALIAS: ${{secrets.ANDROID_KEY_ALIAS}}
      ANDROID_KEY_PASSWORD: ${{secrets.ANDROID_KEY_PASSWORD}}
      ANDROID_STORE_PASSWORD: ${{secrets.ANDROID_STORE_PASSWORD}}
      ANDROID_SIGNING_KEY: ${{secrets.ANDROID_SIGNING_KEY}}
      GOOGLE_SERVICES_KEY: ${{secrets.GOOGLE_SERVICES_KEY}}
      SERVICES_ACCOUNT_KEY: ${{secrets.SERVICES_ACCOUNT_KEY}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install bundler
        run: |
          gem install bundler:2.2.27
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Generate google-services.json file
        run: echo ${{secrets.GOOGLE_SERVICES_KEY}} | base64 -d > app/google-services.json

      - name: Generate service-account.json file
        run: echo ${{secrets.SERVICES_ACCOUNT_KEY}} | base64 -d > fastlane/service-account.json

      - name: Generate .jks file
        run: echo ${{secrets.ANDROID_SIGNING_KEY}} | base64 -d > keys/release.jks

      - name: Upload AAB to Play Store
        run: bundle exec fastlane internal